# Code Generated by Sidekick is for learning and experimentation purposes only.
def factorial(n: int) -> int:
    """Return n! (n factorial)."""
    result = 1
    for i in range(2, n + 1):
        result *= i
    return result


def main() -> None:
    # 1. Classic first step in any language
    print("Hello, World!")

    # 2. Get user input and square it
    number_str = input("Enter a positive integer: ")
    try:
        num = int(number_str)
        if num < 0:
            raise ValueError("Number must be non-negative.")

        print(f"The square of {num} is {num ** 2}")

        # 3. Compute factorial
        print(f"The factorial of {num} is {factorial(num)}")

    except ValueError as err:
        print(f"Invalid input: {err}")


if __name__ == "__main__":
    main()
